data_fields = {
    'N': {
        'c_p': 0,
        'ss_p': 2,
        'c_w': 20,
        'cb': True,
        'construct': True,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Batch': {
        'c_p': 1,
        'ss_p': 3,
        'c_w': 60,
        'cb': False,
        'ss_tr': 'Batch',
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Sample_ID': {
        'c_p': 2,
        'ss_p': 0,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': False,
        'combine': False,
        'value_constraints': False
    },
    'Sample_Name': {
        'c_p': -1,
        'ss_p': 1,
        'c_w': -1,
        'cb': False,
        'construct': False,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Library_ID': {
        'c_p': 4,
        'ss_p': 4,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Sex': {
        'c_p': 3,
        'ss_p': 5,
        'c_w': 30,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': "m,f"
    },
    'I5_Index_ID': {
        'c_p': 5,
        'ss_p': 6,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'index2': {
        'c_p': -1,
        'c_w': -1,
        'ss_p': 7,
        'cb': False,
        'construct': False,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'I7_Index_ID': {
        'c_p': 6,
        'ss_p': 8,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'index': {
        'c_p': -1,
        'ss_p': 9,
        'c_w': -1,
        'cb': False,
        'construct': False,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'I7_Index_ID+I5_Index_ID': {
        'c_p': -1,
        'ss_p': -1,
        'c_w': -1,
        'cb': False,
        'construct': False,
        'ss': False,
        'required': True,
        'duplicates_ok': False,
        'combine': "I7_Index_ID,I5_Index_ID",
        'value_constraints': False
    },
    'Analysis_Def': {
        'c_p': 7,
        'ss_p': 10,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Panel_Target': {
        'c_p':-1,
        'ss_p': 11,
        'c_w': 128,
        'cb': False,
        'construct': False,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Method': {
        'c_p': -1,
        'ss_p': 12,
        'c_w': 128,
        'cb': False,
        'construct': False,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Panel': {
        'c_p': 8,
        'ss_p': 13,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Analysis': {
        'c_p': 9,
        'ss_p': 14,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': True,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
    'Comment': {
        'c_p': 10,
        'ss_p': 15,
        'c_w': 128,
        'cb': False,
        'construct': True,
        'ss': True,
        'required': False,
        'duplicates_ok': True,
        'combine': False,
        'value_constraints': False
    },
}
