# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pref.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(616, 453)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_institute = QtWidgets.QLineEdit(Form)
        self.lineEdit_institute.setObjectName("lineEdit_institute")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_institute)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_configfile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_configfile.setObjectName("horizontalLayout_configfile")
        self.lineEdit_config_file = QtWidgets.QLineEdit(Form)
        self.lineEdit_config_file.setObjectName("lineEdit_config_file")
        self.horizontalLayout_configfile.addWidget(self.lineEdit_config_file)
        self.toolButton_config_file = QtWidgets.QToolButton(Form)
        self.toolButton_config_file.setObjectName("toolButton_config_file")
        self.horizontalLayout_configfile.addWidget(self.toolButton_config_file)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_configfile)
        self.lbl_1 = QtWidgets.QLabel(Form)
        self.lbl_1.setObjectName("lbl_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_indices_file = QtWidgets.QLineEdit(Form)
        self.lineEdit_indices_file.setObjectName("lineEdit_indices_file")
        self.horizontalLayout.addWidget(self.lineEdit_indices_file)
        self.toolButton_indices_file = QtWidgets.QToolButton(Form)
        self.toolButton_indices_file.setObjectName("toolButton_indices_file")
        self.horizontalLayout.addWidget(self.toolButton_indices_file)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_samplesheets_folder = QtWidgets.QLineEdit(Form)
        self.lineEdit_samplesheets_folder.setObjectName("lineEdit_samplesheets_folder")
        self.horizontalLayout_4.addWidget(self.lineEdit_samplesheets_folder)
        self.toolButton_samplesheets_folder = QtWidgets.QToolButton(Form)
        self.toolButton_samplesheets_folder.setObjectName("toolButton_samplesheets_folder")
        self.horizontalLayout_4.addWidget(self.toolButton_samplesheets_folder)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_add_investigator = QtWidgets.QLineEdit(Form)
        self.lineEdit_add_investigator.setObjectName("lineEdit_add_investigator")
        self.horizontalLayout_5.addWidget(self.lineEdit_add_investigator)
        self.pushButton_add_investigator = QtWidgets.QPushButton(Form)
        self.pushButton_add_investigator.setObjectName("pushButton_add_investigator")
        self.horizontalLayout_5.addWidget(self.pushButton_add_investigator)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.listWidget_investigators = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidget_investigators.sizePolicy().hasHeightForWidth())
        self.listWidget_investigators.setSizePolicy(sizePolicy)
        self.listWidget_investigators.setMinimumSize(QtCore.QSize(100, 100))
        self.listWidget_investigators.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_investigators.setMovement(QtWidgets.QListView.Static)
        self.listWidget_investigators.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget_investigators.setObjectName("listWidget_investigators")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.listWidget_investigators)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.pushButton_remove_investigators = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove_investigators.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_investigators.setSizePolicy(sizePolicy)
        self.pushButton_remove_investigators.setObjectName("pushButton_remove_investigators")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_remove_investigators)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_ok = QtWidgets.QPushButton(Form)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Institute"))
        self.label_6.setText(_translate("Form", "Config yaml file"))
        self.toolButton_config_file.setText(_translate("Form", "..."))
        self.lbl_1.setText(_translate("Form", "Indices file"))
        self.toolButton_indices_file.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "SampleSheets folder"))
        self.toolButton_samplesheets_folder.setText(_translate("Form", "..."))
        self.pushButton_add_investigator.setText(_translate("Form", "Add"))
        self.label_5.setText(_translate("Form", "Investigator"))
        self.pushButton_remove_investigators.setText(_translate("Form", "Remove Selected Investigators"))
        self.btn_ok.setText(_translate("Form", "OK"))
        self.btn_cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

