---
# config file for SampleSheetCreator

Instrument: [nextseq,miseq]

Methods:
    Archer_VariantPlex_DNA:
        Header:
            IEMFileVersion: 4
            Workflow: "GenerateFASTQ"
            Application: "FASTQ Only"
            Assay: "Nextera"
            Chemistry: "Amplicon"
        Settings:
            Adapter: "CTGTCTCTTATACACATCT"
            Reads: [151,151]
        Panels:
            Solid_tumor:
                AnalysisDefPathWin: 'C:\Users\parlar\PycharmProjects\SampleSheetCreator\analysis_defs\Archer_VariantPlex_DNA\Solid_tumor'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'                
                Manifests:
                    A: "-"
                PanelTarget: 'NA'
            Myeloid:
                AnalysisDefPathWin: 'C:\Users\parlar\PycharmProjects\SampleSheetCreator\analysis_defs\Archer_VariantPlex_DNA\Myeloid'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'
                Manifests:
                    A: "-"
                PanelTarget: 'NA'
    Agilent_Haloplex_DNA:
        Header:
            IEMFileVersion: 4
            Workflow: "Custom Amplicon"
            Application: "FASTQ Only"
            Assay: "TruSeq LT"
            Chemistry: "Default"
        Settings:
            ReverseComplement: 0
        Panels:
            Cardio:
                AnalysisDefPathWin: 'C:\Users\parlar\PycharmProjects\SampleSheetCreator\analysis_defs\Agilent_Haloplex_DNA\Cardio'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'
                Manifests: 
                    A: '-'
                PanelTarget: 'LKPN_design_III_17150-1413761621.bed'
