---
# Indices file for SampleSheetCreator

Indices:
    Archer_VariantPlex_DNA:
        miseq:
            P7:
                set_A:
                    P7_1: TAAGGCGA
                    P7_2: CGTACTAG
                    P7_3: AGGCAGAA
                    P7_4: TCCTGAGC
                    P7_5: GGACTCCT
                    P7_6: TAGGCATG
                    P7_7: CTCTCTAC
                    P7_8: CAGAGAGG
            P5:
                set_A:
                    RBC1-BC1: ATCCGTAC
                    RBC1-BC2: GTTCACAG
                    RBC1-BC3: TGCTACGA
                    RBC1-BC4: AGACTCAC
                    RBC1-BC5: ATCCAAGC
                    RBC1-BC6: CGCATTCA
                    RBC1-BC7: ATGACACG
                    RBC1-BC8: AACTACGG
                    RBC1-BC9: GAGGCTTA
                    RBC1-BC10: GACTTCGT
                    RBC1-BC11: GTCGTTGT
                    RBC1-BC12: TCTGCTTC
                    RBC1-BC13: GAGGACTT
                    RBC1-BC14: TCCTCGAT
                    RBC1-BC15: AAGCAGGA
                    RBC1-BC16: TTCTAGGC
                    RBC1-BC17: GCGTAACT
                    RBC1-BC18: GTGATCCA
                    RBC1-BC19: GTGCAGTT
                    RBC1-BC20: GACCGTAA
                    RBC1-BC21: TGATCGTC
                    RBC1-BC22: GTTCAAGG
                    RBC1-BC23: CCATTCGT
                    RBC1-BC24: AGTATGCC
                    RBC1-BC25: AGAGACCT
                    RBC1-BC26: TGTGCATG
                    RBC1-BC27: ATAAGCGG
                    RBC1-BC28: CATTCCAC
                    RBC1-BC29: TCCATGTC
                    RBC1-BC30: CATGTGAC
                    RBC1-BC31: AGGAGATC
                    RBC1-BC32: GTCAGTTG
                    RBC1-BC33: CCAACGAA
                    RBC1-BC34: CTCATTGG
                    RBC1-BC35: CCTCAGAA
                    RBC1-BC36: GGATTGAG
                    RBC1-BC37: CCACTTGT
                    RBC1-BC38: TATGACGG
                    RBC1-BC39: CTTCCGTT
                    RBC1-BC40: GGTTACAC
                    RBC1-BC41: CTGTCCAT
                    RBC1-BC42: AGGCACTT
                    RBC1-BC43: CGTCATAC
                    RBC1-BC44: GTCGATCA
                    RBC1-BC45: GTACGTCA
                    RBC1-BC46: CGACGATT
                    RBC1-BC47: ACATCCTC
                    RBC1-BC48: CTGTAGCT
                set_B:
                    RBC2-BC1: AGCATTCC
                    RBC2-BC2: GGCTTGTT
                    RBC2-BC3: TTGGACAC
                    RBC2-BC4: GTTGATCG
                    RBC2-BC5: TCACTACG
                    RBC2-BC6: GTGGAGAA
                    RBC2-BC7: TAGTGCTG
                    RBC2-BC8: GCACACAA
                    RBC2-BC9: AACCTGGT
                    RBC2-BC10: TCAGGTGT
                    RBC2-BC11: TACCATGG
                    RBC2-BC12: CTATGCTG
                    RBC2-BC13: CTGCCATA
                    RBC2-BC14: TGGACGAT
                    RBC2-BC15: CACACACA
                    RBC2-BC16: GTTACCAC
                    RBC2-BC17: CATTCTCC
                    RBC2-BC18: AGGTGTAG
                    RBC2-BC19: ACTCTACG
                    RBC2-BC20: GTGTATGC
                    RBC2-BC21: GTTCAGCT
                    RBC2-BC22: ATAGCCTC
                    RBC2-BC23: TGCTTCCT
                    RBC2-BC24: TGCTGATC
                    RBC2-BC25: TAGAGGTC
                    RBC2-BC26: CGATTACG
                    RBC2-BC27: TCTACCTG
                    RBC2-BC28: ACCTATCC
                    RBC2-BC29: CACTAGGA
                    RBC2-BC30: CCTTAGAG
                    RBC2-BC31: CTCCTACA
                    RBC2-BC32: CGTGTATC
                    RBC2-BC33: TGCCATCA
                    RBC2-BC34: TCGAGACA
                    RBC2-BC35: GTCAGGTA
                    RBC2-BC36: CTCTCAGT
                    RBC2-BC37: TACTTCGG
                    RBC2-BC38: GTATCCTG
                    RBC2-BC39: ACGCAGAT
                    RBC2-BC40: GGTCATTC
                    RBC2-BC41: GGTACACT
                    RBC2-BC42: GCAGACTT
                    RBC2-BC43: GTCTAACC
                    RBC2-BC44: CTCATGAC
                    RBC2-BC45: ACAAGCTG
                    RBC2-BC46: TAGGTACC
                    RBC2-BC47: CAGTGTTC
                    RBC2-BC48: CTGACAAC
                set_C:
                    RBC3-BC1: TCCTGAGT
                    RBC3-BC2: ACGGTACA
                    RBC3-BC3: CAGAACGT
                    RBC3-BC4: CTCCAACT
                    RBC3-BC5: GTTGCAGA
                    RBC3-BC6: CTACAGGT
                    RBC3-BC7: CTGACTCT
                    RBC3-BC8: TGGTACCT
                    RBC3-BC9: TCGTAGTC
                    RBC3-BC10: TGTGAGCA
                    RBC3-BC11: ATTGCTGC
                    RBC3-BC12: GAACTTGC
                    RBC3-BC13: ACGAGACT
                    RBC3-BC14: ACCAGTTC
                    RBC3-BC15: CAAGTCAG
                    RBC3-BC16: GTAGTCTG
                    RBC3-BC17: CGTGTCAA
                    RBC3-BC18: GTAGCGAA
                    RBC3-BC19: ACACGAAG
                    RBC3-BC20: CAATCACC
                    RBC3-BC21: CTCTCTTG
                    RBC3-BC22: CGTATCGA
                    RBC3-BC23: TGAGGATC
                    RBC3-BC24: AGTTGCGT
                    RBC3-BC25: TTCAACGC
                    RBC3-BC26: ATTCGGCT
                    RBC3-BC27: GAAGGTGA
                    RBC3-BC28: ATTCGTGC
                    RBC3-BC29: GATGACTC
                    RBC3-BC30: ATCAGACC
                    RBC3-BC31: CCACATTG
                    RBC3-BC32: GGTCTACT
                    RBC3-BC33: GCCTACTA
                    RBC3-BC34: AGTCAAGG
                    RBC3-BC35: GCGAGAAT
                    RBC3-BC36: GGTTCGAT
                    RBC3-BC37: TCCATAGG
                    RBC3-BC38: TGACCGAA
                    RBC3-BC39: CCATGGTA
                    RBC3-BC40: CGAGTTAC
                    RBC3-BC41: CGTACTCT
                    RBC3-BC42: TTCGAACG
                    RBC3-BC43: AAGGCTTC
                    RBC3-BC44: AACGTGTG
                    RBC3-BC45: GGTACCTT
                    RBC3-BC46: CACAGGAA
                    RBC3-BC47: CATGCCAT
                    RBC3-BC48: GGATACAG
        nextseq:
            P7:
                set_A:
                    P7_1: TAAGGCGA
                    P7_2: CGTACTAG
                    P7_3: AGGCAGAA
                    P7_4: TCCTGAGC
                    P7_5: GGACTCCT
                    P7_6: TAGGCATG
                    P7_7: CTCTCTAC
                    P7_8: CAGAGAGG
            P5:
                set_A:
                    RBC1-BC1: GTACGGAT
                    RBC1-BC2: CTGTGAAC
                    RBC1-BC3: TCGTAGCA
                    RBC1-BC4: GTGAGTCT
                    RBC1-BC5: GCTTGGAT
                    RBC1-BC6: TGAATGCG
                    RBC1-BC7: CGTGTCAT
                    RBC1-BC8: CCGTAGTT
                    RBC1-BC9: TAAGCCTC
                    RBC1-BC10: ACGAAGTC
                    RBC1-BC11: ACAACGAC
                    RBC1-BC12: GAAGCAGA
                    RBC1-BC13: AAGTCCTC
                    RBC1-BC14: ATCGAGGA
                    RBC1-BC15: TCCTGCTT
                    RBC1-BC16: GCCTAGAA
                    RBC1-BC17: AGTTACGC
                    RBC1-BC18: TGGATCAC
                    RBC1-BC19: AACTGCAC
                    RBC1-BC20: TTACGGTC
                    RBC1-BC21: GACGATCA
                    RBC1-BC22: CCTTGAAC
                    RBC1-BC23: ACGAATGG
                    RBC1-BC24: GGCATACT
                    RBC1-BC25: AGGTCTCT
                    RBC1-BC26: CATGCACA
                    RBC1-BC27: CCGCTTAT
                    RBC1-BC28: GTGGAATG
                    RBC1-BC29: GACATGGA
                    RBC1-BC30: GTCACATG
                    RBC1-BC31: GATCTCCT
                    RBC1-BC32: CAACTGAC
                    RBC1-BC33: TTCGTTGG
                    RBC1-BC34: CCAATGAG
                    RBC1-BC35: TTCTGAGG
                    RBC1-BC36: CTCAATCC
                    RBC1-BC37: ACAAGTGG
                    RBC1-BC38: CCGTCATA
                    RBC1-BC39: AACGGAAG
                    RBC1-BC40: GTGTAACC
                    RBC1-BC41: ATGGACAG
                    RBC1-BC42: AAGTGCCT
                    RBC1-BC43: GTATGACG
                    RBC1-BC44: TGATCGAC
                    RBC1-BC45: TGACGTAC
                    RBC1-BC46: AATCGTCG
                    RBC1-BC47: GAGGATGT
                    RBC1-BC48: AGCTACAG
                set_B:
                    RBC2-BC1: GGAATGCT
                    RBC2-BC2: AACAAGCC
                    RBC2-BC3: GTGTCCAA
                    RBC2-BC4: CGATCAAC
                    RBC2-BC5: CGTAGTGA
                    RBC2-BC6: TTCTCCAC
                    RBC2-BC7: CAGCACTA
                    RBC2-BC8: TTGTGTGC
                    RBC2-BC9: ACCAGGTT
                    RBC2-BC10: ACACCTGA
                    RBC2-BC11: CCATGGTA
                    RBC2-BC12: CAGCATAG
                    RBC2-BC13: TATGGCAG
                    RBC2-BC14: ATCGTCCA
                    RBC2-BC15: TGTGTGTG
                    RBC2-BC16: GTGGTAAC
                    RBC2-BC17: GGAGAATG
                    RBC2-BC18: CTACACCT
                    RBC2-BC19: CGTAGAGT
                    RBC2-BC20: GCATACAC
                    RBC2-BC21: AGCTGAAC
                    RBC2-BC22: GAGGCTAT
                    RBC2-BC23: AGGAAGCA
                    RBC2-BC24: GATCAGCA
                    RBC2-BC25: GACCTCTA
                    RBC2-BC26: CGTAATCG
                    RBC2-BC27: CAGGTAGA
                    RBC2-BC28: GGATAGGT
                    RBC2-BC29: TCCTAGTG
                    RBC2-BC30: CTCTAAGG
                    RBC2-BC31: TGTAGGAG
                    RBC2-BC32: GATACACG
                    RBC2-BC33: TGATGGCA
                    RBC2-BC34: TGTCTCGA
                    RBC2-BC35: TACCTGAC
                    RBC2-BC36: ACTGAGAG
                    RBC2-BC37: CCGAAGTA
                    RBC2-BC38: CAGGATAC
                    RBC2-BC39: ATCTGCGT
                    RBC2-BC40: GAATGACC
                    RBC2-BC41: AGTGTACC
                    RBC2-BC42: AAGTCTGC
                    RBC2-BC43: GGTTAGAC
                    RBC2-BC44: GTCATGAG
                    RBC2-BC45: CAGCTTGT
                    RBC2-BC46: GGTACCTA
                    RBC2-BC47: GAACACTG
                    RBC2-BC48: GTTGTCAG
                set_C:
                    RBC3-BC1: ACTCAGGA
                    RBC3-BC2: TGTACCGT
                    RBC3-BC3: ACGTTCTG
                    RBC3-BC4: AGTTGGAG
                    RBC3-BC5: TCTGCAAC
                    RBC3-BC6: ACCTGTAG
                    RBC3-BC7: AGAGTCAG
                    RBC3-BC8: AGGTACCA
                    RBC3-BC9: GACTACGA
                    RBC3-BC10: TGCTCACA
                    RBC3-BC11: GCAGCAAT
                    RBC3-BC12: GCAAGTTC
                    RBC3-BC13: AGTCTCGT
                    RBC3-BC14: GAACTGGT
                    RBC3-BC15: CTGACTTG
                    RBC3-BC16: CAGACTAC
                    RBC3-BC17: TTGACACG
                    RBC3-BC18: TTCGCTAC
                    RBC3-BC19: CTTCGTGT
                    RBC3-BC20: GGTGATTG
                    RBC3-BC21: CAAGAGAG
                    RBC3-BC22: TCGATACG
                    RBC3-BC23: GATCCTCA
                    RBC3-BC24: ACGCAACT
                    RBC3-BC25: GCGTTGAA
                    RBC3-BC26: AGCCGAAT
                    RBC3-BC27: TCACCTTC
                    RBC3-BC28: GCACGAAT
                    RBC3-BC29: GAGTCATC
                    RBC3-BC30: GGTCTGAT
                    RBC3-BC31: CAATGTGG
                    RBC3-BC32: AGTAGACC
                    RBC3-BC33: TAGTAGGC
                    RBC3-BC34: CCTTGACT
                    RBC3-BC35: ATTCTCGC
                    RBC3-BC36: ATCGAACC
                    RBC3-BC37: CCTATGGA
                    RBC3-BC38: TTCGGTCA
                    RBC3-BC39: TACCATGG
                    RBC3-BC40: GTAACTCG
                    RBC3-BC41: AGAGTACG
                    RBC3-BC42: CGTTCGAA
                    RBC3-BC43: GAAGCCTT
                    RBC3-BC44: CACACGTT
                    RBC3-BC45: AAGGTACC
                    RBC3-BC46: TTCCTGTG
                    RBC3-BC47: ATGGCATG
                    RBC3-BC48: CTGTATCC
    Agilent_Haloplex_DNA:
        miseq:
            P7:
                set_A:
                    A01: ATGCCTAA
                    B01: GAATCTGA
                    C01: AACGTGAT
                    D01: CACTTCGA
                    E01: GCCAAGAC
                    F01: GACTAGTA
                    G01: ATTGGCTC
                    H01: GATGAATC
                    A02: AGCAGGAA
                    B02: GAGCTGAA
                    C02: AAACATCG
                    D02: GAGTTAGC
                    E02: CGAACTTA
                    F02: GATAGACA
                    G02: AAGGACAC
                    H02: GACAGTGC
                    A03: ATCATTCC
                    B03: GCCACATA
                    C03: ACCACTGT
                    D03: CTGGCATA
                    E03: ACCTCCAA
                    F03: GCGAGTAA
                    G03: ACTATGCA
                    H03: CGGATTGC
                    A04: AACTCACC
                    B04: GCTAACGA
                    C04: CAGATCTG
                    D04: ATCCTGTA
                    E04: CTGTAGCC
                    F04: GCTCGGTA
                    G04: ACACGACC
                    H04: AGTCACTA
                    A05: AACGCTTA
                    B05: GGAGAACA
                    C05: CATCAAGT
                    D05: AAGGTACA
                    E05: CGCTGATC
                    F05: GGTGCGAA
                    G05: CCTAATCC
                    H05: CTGAGCCA
                    A06: AGCCATGC
                    B06: GTACGCAA
                    C06: AGTACAAG
                    D06: ACATTGGC
                    E06: ATTGAGGA
                    F06: GTCGTAGA
                    G06: AGAGTCAA
                    H06: CCGACAAC
                    A07: ACGTATCA
                    B07: GTCTGTCA
                    C07: CTAAGGTC
                    D07: CGACACAC
                    E07: CCGTGAGA
                    F07: GTGTTCTA
                    G07: CAATGGAA
                    H07: AGCACCTC
                    A08: CAGCGTTA
                    B08: TAGGATGA
                    C08: AGTGGTCA
                    D08: ACAGCAGA
                    E08: CATACCAA
                    F08: TATCAGCA
                    G08: ATAGCGAC
                    H08: ACGCTCGA
                    A09: CTCAATGA
                    B09: TCCGTCTA
                    C09: AGGCTAAC
                    D09: CCATCCTC
                    E09: AGATGTAC
                    F09: TCTTCACA
                    G09: CCGAAGTA
                    H09: CGCATACA
                    A10: AATGTTGC
                    B10: TGAAGAGA
                    C10: AGATCGCA
                    D10: AAGAGATC
                    E10: CAACCACA
                    F10: TGGAACAA
                    G10: CCTCTATC
                    H10: ACAGATTC
                    A11: CCAGTTCA
                    B11: TGGCTTCA
                    C11: CGACTGGA
                    D11: CAAGACTA
                    E11: CCTCCTGA
                    F11: TGGTGGTA
                    G11: AACAACCA
                    H11: AATCCGTC
                    A12: CAAGGAGC
                    B12: TTCACGCA
                    C12: CACCTTAC
                    D12: AAGACGGA
                    E12: ACACAGAA
                    F12: GAACAGGC
                    G12: AACCGAGA
                    H12: ACAAGCTA
            P5:
                set_A:
        nextseq:
            P7:
                set_A:
                    A01: ATGCCTAA
                    B01: GAATCTGA
                    C01: AACGTGAT
                    D01: CACTTCGA
                    E01: GCCAAGAC
                    F01: GACTAGTA
                    G01: ATTGGCTC
                    H01: GATGAATC
                    A02: AGCAGGAA
                    B02: GAGCTGAA
                    C02: AAACATCG
                    D02: GAGTTAGC
                    E02: CGAACTTA
                    F02: GATAGACA
                    G02: AAGGACAC
                    H02: GACAGTGC
                    A03: ATCATTCC
                    B03: GCCACATA
                    C03: ACCACTGT
                    D03: CTGGCATA
                    E03: ACCTCCAA
                    F03: GCGAGTAA
                    G03: ACTATGCA
                    H03: CGGATTGC
                    A04: AACTCACC
                    B04: GCTAACGA
                    C04: CAGATCTG
                    D04: ATCCTGTA
                    E04: CTGTAGCC
                    F04: GCTCGGTA
                    G04: ACACGACC
                    H04: AGTCACTA
                    A05: AACGCTTA
                    B05: GGAGAACA
                    C05: CATCAAGT
                    D05: AAGGTACA
                    E05: CGCTGATC
                    F05: GGTGCGAA
                    G05: CCTAATCC
                    H05: CTGAGCCA
                    A06: AGCCATGC
                    B06: GTACGCAA
                    C06: AGTACAAG
                    D06: ACATTGGC
                    E06: ATTGAGGA
                    F06: GTCGTAGA
                    G06: AGAGTCAA
                    H06: CCGACAAC
                    A07: ACGTATCA
                    B07: GTCTGTCA
                    C07: CTAAGGTC
                    D07: CGACACAC
                    E07: CCGTGAGA
                    F07: GTGTTCTA
                    G07: CAATGGAA
                    H07: AGCACCTC
                    A08: CAGCGTTA
                    B08: TAGGATGA
                    C08: AGTGGTCA
                    D08: ACAGCAGA
                    E08: CATACCAA
                    F08: TATCAGCA
                    G08: ATAGCGAC
                    H08: ACGCTCGA
                    A09: CTCAATGA
                    B09: TCCGTCTA
                    C09: AGGCTAAC
                    D09: CCATCCTC
                    E09: AGATGTAC
                    F09: TCTTCACA
                    G09: CCGAAGTA
                    H09: CGCATACA
                    A10: AATGTTGC
                    B10: TGAAGAGA
                    C10: AGATCGCA
                    D10: AAGAGATC
                    E10: CAACCACA
                    F10: TGGAACAA
                    G10: CCTCTATC
                    H10: ACAGATTC
                    A11: CCAGTTCA
                    B11: TGGCTTCA
                    C11: CGACTGGA
                    D11: CAAGACTA
                    E11: CCTCCTGA
                    F11: TGGTGGTA
                    G11: AACAACCA
                    H11: AATCCGTC
                    A12: CAAGGAGC
                    B12: TTCACGCA
                    C12: CACCTTAC
                    D12: AAGACGGA
                    E12: ACACAGAA
                    F12: GAACAGGC
                    G12: AACCGAGA
                    H12: ACAAGCTA

            P5:
                set_A:
