---
# Indices file for SampleSheetCreator

Indices:
    Archer_VariantPlex_DNA:
        miseq:
            P7:
                A:
                    A-P7_1: TAAGGCGA
                    A-P7_2: CGTACTAG
                    A-P7_3: AGGCAGAA
                    A-P7_4: TCCTGAGC
                    A-P7_5: GGACTCCT
                    A-P7_6: TAGGCATG
                    A-P7_7: CTCTCTAC
                    A-P7_8: CAGAGAGG
            P5:
                A:
                    A-BC1: ATCCGTAC
                    A-BC2: GTTCACAG
                    A-BC3: TGCTACGA
                    A-BC4: AGACTCAC
                    A-BC5: ATCCAAGC
                    A-BC6: CGCATTCA
                    A-BC7: ATGACACG
                    A-BC8: AACTACGG
                    A-BC9: GAGGCTTA
                    A-BC10: GACTTCGT
                    A-BC11: GTCGTTGT
                    A-BC12: TCTGCTTC
                    A-BC13: GAGGACTT
                    A-BC14: TCCTCGAT
                    A-BC15: AAGCAGGA
                    A-BC16: TTCTAGGC
                    A-BC17: GCGTAACT
                    A-BC18: GTGATCCA
                    A-BC19: GTGCAGTT
                    A-BC20: GACCGTAA
                    A-BC21: TGATCGTC
                    A-BC22: GTTCAAGG
                    A-BC23: CCATTCGT
                    A-BC24: AGTATGCC
                    A-BC25: AGAGACCT
                    A-BC26: TGTGCATG
                    A-BC27: ATAAGCGG
                    A-BC28: CATTCCAC
                    A-BC29: TCCATGTC
                    A-BC30: CATGTGAC
                    A-BC31: AGGAGATC
                    A-BC32: GTCAGTTG
                    A-BC33: CCAACGAA
                    A-BC34: CTCATTGG
                    A-BC35: CCTCAGAA
                    A-BC36: GGATTGAG
                    A-BC37: CCACTTGT
                    A-BC38: TATGACGG
                    A-BC39: CTTCCGTT
                    A-BC40: GGTTACAC
                    A-BC41: CTGTCCAT
                    A-BC42: AGGCACTT
                    A-BC43: CGTCATAC
                    A-BC44: GTCGATCA
                    A-BC45: GTACGTCA
                    A-BC46: CGACGATT
                    A-BC47: ACATCCTC
                    A-BC48: CTGTAGCT
                B:
                    B-BC1: AGCATTCC
                    B-BC2: GGCTTGTT
                    B-BC3: TTGGACAC
                    B-BC4: GTTGATCG
                    B-BC5: TCACTACG
                    B-BC6: GTGGAGAA
                    B-BC7: TAGTGCTG
                    B-BC8: GCACACAA
                    B-BC9: AACCTGGT
                    B-BC10: TCAGGTGT
                    B-BC11: TACCATGG
                    B-BC12: CTATGCTG
                    B-BC13: CTGCCATA
                    B-BC14: TGGACGAT
                    B-BC15: CACACACA
                    B-BC16: GTTACCAC
                    B-BC17: CATTCTCC
                    B-BC18: AGGTGTAG
                    B-BC19: ACTCTACG
                    B-BC20: GTGTATGC
                    B-BC21: GTTCAGCT
                    B-BC22: ATAGCCTC
                    B-BC23: TGCTTCCT
                    B-BC24: TGCTGATC
                    B-BC25: TAGAGGTC
                    B-BC26: CGATTACG
                    B-BC27: TCTACCTG
                    B-BC28: ACCTATCC
                    B-BC29: CACTAGGA
                    B-BC30: CCTTAGAG
                    B-BC31: CTCCTACA
                    B-BC32: CGTGTATC
                    B-BC33: TGCCATCA
                    B-BC34: TCGAGACA
                    B-BC35: GTCAGGTA
                    B-BC36: CTCTCAGT
                    B-BC37: TACTTCGG
                    B-BC38: GTATCCTG
                    B-BC39: ACGCAGAT
                    B-BC40: GGTCATTC
                    B-BC41: GGTACACT
                    B-BC42: GCAGACTT
                    B-BC43: GTCTAACC
                    B-BC44: CTCATGAC
                    B-BC45: ACAAGCTG
                    B-BC46: TAGGTACC
                    B-BC47: CAGTGTTC
                    B-BC48: CTGACAAC
                C:
                    C-BC1: TCCTGAGT
                    C-BC2: ACGGTACA
                    C-BC3: CAGAACGT
                    C-BC4: CTCCAACT
                    C-BC5: GTTGCAGA
                    C-BC6: CTACAGGT
                    C-BC7: CTGACTCT
                    C-BC8: TGGTACCT
                    C-BC9: TCGTAGTC
                    C-BC10: TGTGAGCA
                    C-BC11: ATTGCTGC
                    C-BC12: GAACTTGC
                    C-BC13: ACGAGACT
                    C-BC14: ACCAGTTC
                    C-BC15: CAAGTCAG
                    C-BC16: GTAGTCTG
                    C-BC17: CGTGTCAA
                    C-BC18: GTAGCGAA
                    C-BC19: ACACGAAG
                    C-BC20: CAATCACC
                    C-BC21: CTCTCTTG
                    C-BC22: CGTATCGA
                    C-BC23: TGAGGATC
                    C-BC24: AGTTGCGT
                    C-BC25: TTCAACGC
                    C-BC26: ATTCGGCT
                    C-BC27: GAAGGTGA
                    C-BC28: ATTCGTGC
                    C-BC29: GATGACTC
                    C-BC30: ATCAGACC
                    C-BC31: CCACATTG
                    C-BC32: GGTCTACT
                    C-BC33: GCCTACTA
                    C-BC34: AGTCAAGG
                    C-BC35: GCGAGAAT
                    C-BC36: GGTTCGAT
                    C-BC37: TCCATAGG
                    C-BC38: TGACCGAA
                    C-BC39: CCATGGTA
                    C-BC40: CGAGTTAC
                    C-BC41: CGTACTCT
                    C-BC42: TTCGAACG
                    C-BC43: AAGGCTTC
                    C-BC44: AACGTGTG
                    C-BC45: GGTACCTT
                    C-BC46: CACAGGAA
                    C-BC47: CATGCCAT
                    C-BC48: GGATACAG
        nextseq:
            P7:
                A:
                    A-P7_1: TAAGGCGA
                    A-P7_2: CGTACTAG
                    A-P7_3: AGGCAGAA
                    A-P7_4: TCCTGAGC
                    A-P7_5: GGACTCCT
                    A-P7_6: TAGGCATG
                    A-P7_7: CTCTCTAC
                    A-P7_8: CAGAGAGG
            P5:
                A:
                    A-BC1: GTACGGAT
                    A-BC2: CTGTGAAC
                    A-BC3: TCGTAGCA
                    A-BC4: GTGAGTCT
                    A-BC5: GCTTGGAT
                    A-BC6: TGAATGCG
                    A-BC7: CGTGTCAT
                    A-BC8: CCGTAGTT
                    A-BC9: TAAGCCTC
                    A-BC10: ACGAAGTC
                    A-BC11: ACAACGAC
                    A-BC12: GAAGCAGA
                    A-BC13: AAGTCCTC
                    A-BC14: ATCGAGGA
                    A-BC15: TCCTGCTT
                    A-BC16: GCCTAGAA
                    A-BC17: AGTTACGC
                    A-BC18: TGGATCAC
                    A-BC19: AACTGCAC
                    A-BC20: TTACGGTC
                    A-BC21: GACGATCA
                    A-BC22: CCTTGAAC
                    A-BC23: ACGAATGG
                    A-BC24: GGCATACT
                    A-BC25: AGGTCTCT
                    A-BC26: CATGCACA
                    A-BC27: CCGCTTAT
                    A-BC28: GTGGAATG
                    A-BC29: GACATGGA
                    A-BC30: GTCACATG
                    A-BC31: GATCTCCT
                    A-BC32: CAACTGAC
                    A-BC33: TTCGTTGG
                    A-BC34: CCAATGAG
                    A-BC35: TTCTGAGG
                    A-BC36: CTCAATCC
                    A-BC37: ACAAGTGG
                    A-BC38: CCGTCATA
                    A-BC39: AACGGAAG
                    A-BC40: GTGTAACC
                    A-BC41: ATGGACAG
                    A-BC42: AAGTGCCT
                    A-BC43: GTATGACG
                    A-BC44: TGATCGAC
                    A-BC45: TGACGTAC
                    A-BC46: AATCGTCG
                    A-BC47: GAGGATGT
                    A-BC48: AGCTACAG
                B:
                    B-BC1: GGAATGCT
                    B-BC2: AACAAGCC
                    B-BC3: GTGTCCAA
                    B-BC4: CGATCAAC
                    B-BC5: CGTAGTGA
                    B-BC6: TTCTCCAC
                    B-BC7: CAGCACTA
                    B-BC8: TTGTGTGC
                    B-BC9: ACCAGGTT
                    B-BC10: ACACCTGA
                    B-BC11: CCATGGTA
                    B-BC12: CAGCATAG
                    B-BC13: TATGGCAG
                    B-BC14: ATCGTCCA
                    B-BC15: TGTGTGTG
                    B-BC16: GTGGTAAC
                    B-BC17: GGAGAATG
                    B-BC18: CTACACCT
                    B-BC19: CGTAGAGT
                    B-BC20: GCATACAC
                    B-BC21: AGCTGAAC
                    B-BC22: GAGGCTAT
                    B-BC23: AGGAAGCA
                    B-BC24: GATCAGCA
                    B-BC25: GACCTCTA
                    B-BC26: CGTAATCG
                    B-BC27: CAGGTAGA
                    B-BC28: GGATAGGT
                    B-BC29: TCCTAGTG
                    B-BC30: CTCTAAGG
                    B-BC31: TGTAGGAG
                    B-BC32: GATACACG
                    B-BC33: TGATGGCA
                    B-BC34: TGTCTCGA
                    B-BC35: TACCTGAC
                    B-BC36: ACTGAGAG
                    B-BC37: CCGAAGTA
                    B-BC38: CAGGATAC
                    B-BC39: ATCTGCGT
                    B-BC40: GAATGACC
                    B-BC41: AGTGTACC
                    B-BC42: AAGTCTGC
                    B-BC43: GGTTAGAC
                    B-BC44: GTCATGAG
                    B-BC45: CAGCTTGT
                    B-BC46: GGTACCTA
                    B-BC47: GAACACTG
                    B-BC48: GTTGTCAG
                C:
                    C-BC1: ACTCAGGA
                    C-BC2: TGTACCGT
                    C-BC3: ACGTTCTG
                    C-BC4: AGTTGGAG
                    C-BC5: TCTGCAAC
                    C-BC6: ACCTGTAG
                    C-BC7: AGAGTCAG
                    C-BC8: AGGTACCA
                    C-BC9: GACTACGA
                    C-BC10: TGCTCACA
                    C-BC11: GCAGCAAT
                    C-BC12: GCAAGTTC
                    C-BC13: AGTCTCGT
                    C-BC14: GAACTGGT
                    C-BC15: CTGACTTG
                    C-BC16: CAGACTAC
                    C-BC17: TTGACACG
                    C-BC18: TTCGCTAC
                    C-BC19: CTTCGTGT
                    C-BC20: GGTGATTG
                    C-BC21: CAAGAGAG
                    C-BC22: TCGATACG
                    C-BC23: GATCCTCA
                    C-BC24: ACGCAACT
                    C-BC25: GCGTTGAA
                    C-BC26: AGCCGAAT
                    C-BC27: TCACCTTC
                    C-BC28: GCACGAAT
                    C-BC29: GAGTCATC
                    C-BC30: GGTCTGAT
                    C-BC31: CAATGTGG
                    C-BC32: AGTAGACC
                    C-BC33: TAGTAGGC
                    C-BC34: CCTTGACT
                    C-BC35: ATTCTCGC
                    C-BC36: ATCGAACC
                    C-BC37: CCTATGGA
                    C-BC38: TTCGGTCA
                    C-BC39: TACCATGG
                    C-BC40: GTAACTCG
                    C-BC41: AGAGTACG
                    C-BC42: CGTTCGAA
                    C-BC43: GAAGCCTT
                    C-BC44: CACACGTT
                    C-BC45: AAGGTACC
                    C-BC46: TTCCTGTG
                    C-BC47: ATGGCATG
                    C-BC48: CTGTATCC
    Agilent_Haloplex_DNA:
        miseq:
            P7:
                A:
                    A-A01: ATGCCTAA
                    A-B01: GAATCTGA
                    A-C01: AACGTGAT
                    A-D01: CACTTCGA
                    A-E01: GCCAAGAC
                    A-F01: GACTAGTA
                    A-G01: ATTGGCTC
                    A-H01: GATGAATC
                    A-A02: AGCAGGAA
                    A-B02: GAGCTGAA
                    A-C02: AAACATCG
                    A-D02: GAGTTAGC
                    A-E02: CGAACTTA
                    A-F02: GATAGACA
                    A-G02: AAGGACAC
                    A-H02: GACAGTGC
                    A-A03: ATCATTCC
                    A-B03: GCCACATA
                    A-C03: ACCACTGT
                    A-D03: CTGGCATA
                    A-E03: ACCTCCAA
                    A-F03: GCGAGTAA
                    A-G03: ACTATGCA
                    A-H03: CGGATTGC
                    A-A04: AACTCACC
                    A-B04: GCTAACGA
                    A-C04: CAGATCTG
                    A-D04: ATCCTGTA
                    A-E04: CTGTAGCC
                    A-F04: GCTCGGTA
                    A-G04: ACACGACC
                    A-H04: AGTCACTA
                    A-A05: AACGCTTA
                    A-B05: GGAGAACA
                    A-C05: CATCAAGT
                    A-D05: AAGGTACA
                    A-E05: CGCTGATC
                    A-F05: GGTGCGAA
                    A-G05: CCTAATCC
                    A-H05: CTGAGCCA
                    A-A06: AGCCATGC
                    A-B06: GTACGCAA
                    A-C06: AGTACAAG
                    A-D06: ACATTGGC
                    A-E06: ATTGAGGA
                    A-F06: GTCGTAGA
                    A-G06: AGAGTCAA
                    A-H06: CCGACAAC
                    A-A07: ACGTATCA
                    A-B07: GTCTGTCA
                    A-C07: CTAAGGTC
                    A-D07: CGACACAC
                    A-E07: CCGTGAGA
                    A-F07: GTGTTCTA
                    A-G07: CAATGGAA
                    A-H07: AGCACCTC
                    A-A08: CAGCGTTA
                    A-B08: TAGGATGA
                    A-C08: AGTGGTCA
                    A-D08: ACAGCAGA
                    A-E08: CATACCAA
                    A-F08: TATCAGCA
                    A-G08: ATAGCGAC
                    A-H08: ACGCTCGA
                    A-A09: CTCAATGA
                    A-B09: TCCGTCTA
                    A-C09: AGGCTAAC
                    A-D09: CCATCCTC
                    A-E09: AGATGTAC
                    A-F09: TCTTCACA
                    A-G09: CCGAAGTA
                    A-H09: CGCATACA
                    A-A10: AATGTTGC
                    A-B10: TGAAGAGA
                    A-C10: AGATCGCA
                    A-D10: AAGAGATC
                    A-E10: CAACCACA
                    A-F10: TGGAACAA
                    A-G10: CCTCTATC
                    A-H10: ACAGATTC
                    A-A11: CCAGTTCA
                    A-B11: TGGCTTCA
                    A-C11: CGACTGGA
                    A-D11: CAAGACTA
                    A-E11: CCTCCTGA
                    A-F11: TGGTGGTA
                    A-G11: AACAACCA
                    A-H11: AATCCGTC
                    A-A12: CAAGGAGC
                    A-B12: TTCACGCA
                    A-C12: CACCTTAC
                    A-D12: AAGACGGA
                    A-E12: ACACAGAA
                    A-F12: GAACAGGC
                    A-G12: AACCGAGA
                    A-H12: ACAAGCTA
            P5:
                A:
        nextseq:
            P7:
                A:
                    A-A01: ATGCCTAA
                    A-B01: GAATCTGA
                    A-C01: AACGTGAT
                    A-D01: CACTTCGA
                    A-E01: GCCAAGAC
                    A-F01: GACTAGTA
                    A-G01: ATTGGCTC
                    A-H01: GATGAATC
                    A-A02: AGCAGGAA
                    A-B02: GAGCTGAA
                    A-C02: AAACATCG
                    A-D02: GAGTTAGC
                    A-E02: CGAACTTA
                    A-F02: GATAGACA
                    A-G02: AAGGACAC
                    A-H02: GACAGTGC
                    A-A03: ATCATTCC
                    A-B03: GCCACATA
                    A-C03: ACCACTGT
                    A-D03: CTGGCATA
                    A-E03: ACCTCCAA
                    A-F03: GCGAGTAA
                    A-G03: ACTATGCA
                    A-H03: CGGATTGC
                    A-A04: AACTCACC
                    A-B04: GCTAACGA
                    A-C04: CAGATCTG
                    A-D04: ATCCTGTA
                    A-E04: CTGTAGCC
                    A-F04: GCTCGGTA
                    A-G04: ACACGACC
                    A-H04: AGTCACTA
                    A-A05: AACGCTTA
                    A-B05: GGAGAACA
                    A-C05: CATCAAGT
                    A-D05: AAGGTACA
                    A-E05: CGCTGATC
                    A-F05: GGTGCGAA
                    A-G05: CCTAATCC
                    A-H05: CTGAGCCA
                    A-A06: AGCCATGC
                    A-B06: GTACGCAA
                    A-C06: AGTACAAG
                    A-D06: ACATTGGC
                    A-E06: ATTGAGGA
                    A-F06: GTCGTAGA
                    A-G06: AGAGTCAA
                    A-H06: CCGACAAC
                    A-A07: ACGTATCA
                    A-B07: GTCTGTCA
                    A-C07: CTAAGGTC
                    A-D07: CGACACAC
                    A-E07: CCGTGAGA
                    A-F07: GTGTTCTA
                    A-G07: CAATGGAA
                    A-H07: AGCACCTC
                    A-A08: CAGCGTTA
                    A-B08: TAGGATGA
                    A-C08: AGTGGTCA
                    A-D08: ACAGCAGA
                    A-E08: CATACCAA
                    A-F08: TATCAGCA
                    A-G08: ATAGCGAC
                    A-H08: ACGCTCGA
                    A-A09: CTCAATGA
                    A-B09: TCCGTCTA
                    A-C09: AGGCTAAC
                    A-D09: CCATCCTC
                    A-E09: AGATGTAC
                    A-F09: TCTTCACA
                    A-G09: CCGAAGTA
                    A-H09: CGCATACA
                    A-A10: AATGTTGC
                    A-B10: TGAAGAGA
                    A-C10: AGATCGCA
                    A-D10: AAGAGATC
                    A-E10: CAACCACA
                    A-F10: TGGAACAA
                    A-G10: CCTCTATC
                    A-H10: ACAGATTC
                    A-A11: CCAGTTCA
                    A-B11: TGGCTTCA
                    A-C11: CGACTGGA
                    A-D11: CAAGACTA
                    A-E11: CCTCCTGA
                    A-F11: TGGTGGTA
                    A-G11: AACAACCA
                    A-H11: AATCCGTC
                    A-A12: CAAGGAGC
                    A-B12: TTCACGCA
                    A-C12: CACCTTAC
                    A-D12: AAGACGGA
                    A-E12: ACACAGAA
                    A-F12: GAACAGGC
                    A-G12: AACCGAGA
                    A-H12: ACAAGCTA

            P5:
                A:
